# Generated by Django 4.2.7 on 2026-04-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_type',
            field=models.CharField(choices=[('excluding', 'Tax Excluding'), ('including', 'Tax Including')], default='excluding', max_length=10),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='api.vendor'),
        ),
    ]
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='tax_type',
            field=models.CharField(
                choices=[('excluding', 'Tax Excluding'), ('including', 'Tax Including')],
                default='excluding',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='vendor',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='purchase_returns',
                to='api.vendor',
            ),
        ),
    ]
