# Generated by Django 4.2.7 on 2026-04-19 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_purchase_tax_type_purchasereturn_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_view_direct_report',
            field=models.BooleanField(default=True),
        ),
    ]
