# Generated by Django 4.2.7 on 2026-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userpermission_can_view_direct_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='can_access_direct_sale',
            field=models.BooleanField(default=True),
        ),
    ]
