# Generated by Django 4.2.7 on 2026-04-20 13:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userpermission_can_access_direct_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cash_card', 'Cash & Card'), ('cash_upi', 'Cash & UPI')], default='cash', max_length=10)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('card_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('upi_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directsale',
            name='sale_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='ItemReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('return_type', models.CharField(choices=[('customer_return', 'Customer Return'), ('damaged', 'Damaged'), ('expired', 'Expired')], default='customer_return', max_length=20)),
                ('item_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='api.itemreturn')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_returns', to='api.product')),
                ('sale_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_lines', to='api.salebill')),
            ],
        ),
        migrations.CreateModel(
            name='InternalSaleBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='api.internalsalemaster')),
            ],
        ),
        migrations.AddField(
            model_name='internalsale',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='api.internalsalebill'),
        ),
    ]
