# Generated by Django 4.2.7 on 2026-04-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemreturn_directsale_sale_number_itemreturnline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasereturn',
            name='return_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
