# Generated by Django 4.2.7 on 2026-04-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_physicalstockrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
