# Generated by Django 4.2.7 on 2026-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_saleitem_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directsale',
            name='sale_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='internalsalebill',
            name='sale_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='itemreturn',
            name='return_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='physicalstockrequest',
            name='request_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasebill',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereturn',
            name='return_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='salebill',
            name='bill_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
