# Generated by Django 4.2.7 on 2026-04-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_directsale_sale_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
