# Generated by Django 4.2.7 on 2026-04-28 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_kcbill_kcpurchase_kcsaleitem_kcstock_kcstoreissue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcstockline',
            name='carry_forward',
            field=models.BooleanField(default=False),
        ),
    ]
