# Generated by Django 4.2.7 on 2026-04-28 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_kcstockline_carry_forward'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcsaleitem',
            name='purchase_required',
            field=models.BooleanField(default=False),
        ),
    ]
