# Generated by Django 4.2.7 on 2026-04-28 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_kcsaleitem_purchase_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpermission',
            name='kc_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userpermission',
            name='kc_delete_bill',
            field=models.BooleanField(default=False),
        ),
    ]
