# Generated by Django 4.2.7 on 2026-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userpermission_kc_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kcbill',
            name='card_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='kcbill',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='kcbill',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('upi', 'UPI'), ('cash_card', 'Cash & Card'), ('cash_upi', 'Cash & UPI')], default='cash', max_length=10),
        ),
        migrations.AddField(
            model_name='kcbill',
            name='upi_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
