# Generated by Django 4.2.7 on 2026-04-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_kcclosingstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasebill',
            name='round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
